-- Query 1: How many permits are issued for students, visitors, and employees each?

SELECT permit_type,COUNT(customer_id) AS count_by_permit_type
FROM customers
JOIN permit_type_price
USING(permit_id)
GROUP BY 1;


-- Query 2: What are the different vehicle types used by permit holders?

SELECT permit_type, vehicle_type, COUNT(*)
FROM customers
JOIN permit_type_price
USING(permit_id)
GROUP BY 1,2;


-- Query 3: What is the number of permits issued by permit names?

SELECT permit_type, permit_name, COUNT(customer_id) AS count_by_permit_type
FROM customers
JOIN permit_type_price
USING(permit_id)
GROUP BY 2
ORDER BY 3 DESC;


-- Query 4: How many vehicles are parked on a random day categorized by permit_type.

SELECT Permit_Name, Permit_Type, count(*) as "No. of vehicles parked on a Random Day"
FROM occupancy JOIN customers USING (customer_id)
JOIN permit_type_price USING (permit_id)
WHERE DATE(Check_In_DateTime) = "2019-11-05"
AND DATE(Check_Out_DAteTime) = "2019-11-05"
GROUP BY Permit_Name
ORDER BY 3 DESC;


-- Query 5: Which lot is preferred the most to park? 

SELECT lot_name as most_used_lot, max(permit_count) as permit_count
FROM (select lot_name as lot_name, permit_type as permit_type,count(permit_id) as permit_count
FROM parking_lot
JOIN occupancy USING (parking_lot_id)
JOIN customers USING (customer_id)
JOIN permit_type_price USING (permit_id)
GROUP BY 1
ORDER BY 3 DESC) as t
GROUP BY 1;


-- Query 6: What is the occupancy distribution in different lots by permit type? 

SELECT t.lot_name AS most_used_lot,t.permit_type,max(permit_count) AS 
    permit_count
FROM (select pl.lot_name AS lot_name, pp.permit_type AS 
permit_type,count(permit_id) AS permit_count
FROM parking_lot pl
JOIN occupancy o USING (parking_lot_id)
JOIN customers c USING (customer_id)
JOIN permit_type_price pp USING (permit_id)
GROUP BY 1,2
ORDER BY 3 DESC) AS t
GROUP BY 1,2;

-- Query 7: How many vehicles by permit type that are parked for more than three days in different lots?

SELECT ptp.permit_type,ptp.permit_name,pl.lot_name,COUNT(pl.lot_name) AS "# of vehicles parked over 3 days"
FROM occupancy o
JOIN parking_lot pl
ON o.parking_lot_id=pl.parking_lot_id
JOIN customers c
ON o.customer_id=c.customer_id
JOIN permit_type_price ptp
ON ptp.permit_id=c.permit_id
WHERE timestampdiff(day,o.check_in_datetime,o.check_out_datetime)>3
GROUP BY 2
ORDER BY 3 DESC;



-- Query 8: What is the revenue generated by each citation type?

SELECT cp.citation_type, COUNT(cc.citation_penalty_id) AS "# of citations", 
COUNT(cc.citation_penalty_id)*penalty_price AS "Total income from citations ($)"
FROM customer_citation cc, citation_penalty cp
where cp.penalty_id = cc.citation_penalty_id
GROUP BY 1
ORDER BY 2 DESC;


